### ISSUE TITLE
Add before/after images to README

### ISSUE THREAD

**Issue by zorab47** [zorab47/active_admin-subnav#2]

**Comment by reneweteling** [comment]
Here you go :)

![image](https://cloud.githubusercontent.com/assets/3830933/14554525/e272a988-02ed-11e6-8fea-95e650660ee7.png)

![image](https://cloud.githubusercontent.com/assets/3830933/14554530/e8a7c31a-02ed-11e6-8e13-2c91ebd1cf42.png)

**Comment by zorab47** [comment]
Added a sample image to the README. Thanks for the PR.
