### ISSUE TITLE
Depreciation Warning for newer Sprockets

### ISSUE THREAD

**Issue by wspurgin** [zorab47/active_admin-subnav#4]
Using Arbre, I get the following depreciation warning after upgrading to sprockets 3.6.3 and sprockets-rails 3.1.1:

```
DEPRECATION WARNING: Extra .css in SCSS file is unnecessary. Rename /var/lib/gems/2.1.0/gems/active_admin-subnav-0.0.1/app/assets/stylesheets/active_admin/subnav.css.scss to /var/lib/gems/2.1.0/gems/active_admin-subnav-0.0.1/app/assets/st
ylesheets/active_admin/subnav.scss
```

Seems like a simple rename should do the trick, but I wanted to bring it to your attention.

**Comment by zorab47** [comment]
Fixed those deprecation warnings in v1.0.0
