### ISSUE TITLE
belongs_to 'Place holder' ?

### ISSUE THREAD

**Issue by mabdelfattah** [zorab47/active_admin-subnav#8]
Currently if you make 'Parent' in active_admin menu, it'll be a place holder (not linked to a page). I want to do the same with sub-menu, here's an example:

Main Menu (Place Holder)
- Sub Menu 1  (Link)
- Sub Menu 2 (Place Holder)
-- Sub Sub Menu 1 (Link)
-- Sub Sub Menu 2 (Link)

**Comment by jstumbaugh** [comment]
Currently, we support place holders in the subnav.

Given the structure of the menu:

- Profile (resource)
- Data (resource)
   - Users (resource)
   - Reports (place holder)
      - Daily Active Users (page)
      - Unsubscribed Users (resource)
- Logout

Both the Daily Active Users page and Unsubscribed Users resource can be created by the following:
 
```ruby
ActiveAdmin.register_page "Daily Active Users" do
  belongs_to :data
  menu parent: "Reports"
end
```

**Comment by mabdelfattah** [comment]
Thank you.
